spring:
  application:
    name: image-generation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/igp
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://curious-glider-64.clerk.accounts.dev

server:
  port: 8080

fal-ai:
  webhook-url: https://c850508f55be.ngrok-free.app
access-key: ${access-key}
secret-key: ${secret-key}
bucket-name: ${bucket-name}
endpoint: ${endpoint}

