spring:
  application:
    name: image-generation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/igp
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
